Rails no const VERSION
```
dev >> Rails
NameError: uninitialized constant Rails
from (pry):3:in `__pry__'
dev >> require 'web-console'
=> true
dev >> Rails
=> Rails
dev >> Rails::VERSION
NameError: uninitialized constant Rails::VERSION
Did you mean?  Version
from (pry):8:in `__pry__'
dev >> Rails.const_defined?(:VERSION)
=> false
dev >> Rails::VERSION = "3.3.3"
=> "3.3.3"
dev >> Rails.const_defined?(:VERSION)
=> true
```